name: ClanSystem
version: '${project.version}'
main: de.zorryno.clansystem.Main
api-version: 1.21.4
author: "zorryno"
description: "Clan System by zorryno"
commands:
  clan:
    description: "Command to Manage Clans"
    usage: "/clan"
  clanchat:
    aliases:
      - "cc"
    description: "Write a message to the Clan"
    usage: "/clan [message]"
